### ISSUE TITLE
Oddness from the script runner, when using dependent scripts.

### ISSUE THREAD

**Issue by jhujasonw** [mprov-ng/mprov_jobserver#60]
```
Oct 31 15:59:55 testcluster.marcc.jhu.edu mprov_jobserver[969320]: Error: Unresolvable Dependancies, make sure it's listed in distro, group, or entity scripts:
Oct 31 15:59:55 testcluster.marcc.jhu.edu mprov_jobserver[969320]:          'install_mprov_jobserversh'
Oct 31 15:59:55 testcluster.marcc.jhu.edu mprov_jobserver[969320]: Exception in thread <class 'mprov_jobserver.plugins.script_runner.script_runner'>:
Oct 31 15:59:55 testcluster.marcc.jhu.edu mprov_jobserver[969320]: Traceback (most recent call last):
Oct 31 15:59:55 testcluster.marcc.jhu.edu mprov_jobserver[969320]:   File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
Oct 31 15:59:55 testcluster.marcc.jhu.edu mprov_jobserver[969320]:     self.run()
Oct 31 15:59:55 testcluster.marcc.jhu.edu mprov_jobserver[969320]:   File "/usr/local/lib/python3.8/site-packages/mprov_jobserver/plugins/plugin.py", line 36, in run
Oct 31 15:59:55 testcluster.marcc.jhu.edu mprov_jobserver[969320]:     self.handle_jobs()
Oct 31 15:59:55 testcluster.marcc.jhu.edu mprov_jobserver[969320]:   File "/usr/local/lib/python3.8/site-packages/mprov_jobserver/plugins/script_runner.py", line 280, in handle_jobs
Oct 31 15:59:55 testcluster.marcc.jhu.edu mprov_jobserver[969320]:     for step in scriptDeps:
Oct 31 15:59:55 testcluster.marcc.jhu.edu mprov_jobserver[969320]: TypeError: 'NoneType' object is not iterable
```

**Comment by jhujasonw** [comment]
Yeah no, that was not a bug.... it was user error.  The script in question was definitely NOT included in any of the listed places.  This was the script running doing EXACTLY what it should.  Situation Normal.
